### ISSUE TITLE
포인트 URL 페이지에서 "포인트 수집" 버튼 클릭시 서버에 에러 로그 발생

### ISSUE THREAD

**Issue by hajubal** [hajubal/pickupcoins#14]
INFO  24-03-12 12:04:35[http-nio-8080-exec-7] [p6spy:60] - 1710245075743|0|commit|connection 71377|url jdbc:mysql://coin-mysql:3306/coin||
INFO  24-03-12 12:04:35[reactor-http-epoll-4] [m.s.h.coins.service.ExchangeService:61] - 로그인이 풀린 사용자: hanetflix, 사이트: naver, cookie: NNB=LVYDB2JFDOSWK; PM_CK_loc=5d92a14f82f7d0a671f998b72623040a55d297f9e68bd497dc369bc94308f584; NM_srt_chzzk=1; nid_inf=590805292; NID_AUT=....vtVocDA5CCyDkXO+hZSXlJXIptb1xRWvgpCWAr44E=
ERROR 24-03-12 12:04:35[reactor-http-epoll-4] [reactor.core.publisher.Operators:324] - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: org.hibernate.LazyInitializationException: could not initialize proxy [me.synology.hajubal.coins.entity.SiteUser#1] - no Session
        at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:702)
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by hajubal** [comment]
lamda 로 넘긴 entity 객체가 영속성의 범위를 벗어나서 발생한 문제.

**Comment by hajubal** [comment]
수정 중 slack 전송안되는 문제를 발견하여 해당 문제도 수정.

slack send payload 형식이 변경되었음. 기존: 문자열 -> json 형식

version: 1.0.5 -> 1.0.6
